- Módulo (Paquete) -> Catálogo de funciones 

- Archivo Python de nombre X 

- Importación completa, específica o alías
    - Import x
    - From x import -
    - Import x as x
    
Módulos populares para el análisis de datos 
- Numpy: librería para cálculo numérico, colecciones de datos en una y varias dimensiones
- Pandas: librería de manejo de estructuras de datos, archivos e importación. 
    - Dataframe y la Serie 
    - Leer y escribir archivos de excel, csv, html, json, o xml 
- Matplotlib: librería para visualización de datos 
    - Otras librerías: seaborn, plotly (gráficos interactivos) y bokeh 


### Numpy 

- Añade a las estructuras de datos conocidas como ARRAYS, estructuras de varias dimensiones, *con elementos de un mismo tipo*  . 
- Un array es una estructura que tendrá un formato de tabla o cuadricula. Arrays tienen ejes (1, 2 ,3) 

#### Creación

In [4]:
import numpy as np # alias comunmente utilizado 

In [3]:
## Instalamos numpy 
!pip install numpy

In [8]:
# ¿como creo arrays con numpy? 
edades = [25, 36, 24 , 25 , 10 , 12 ]
arr_edades = np.array(edades) #vector 
print(type(edades))
print(arr_edades)

<class 'list'>
[25 36 24 25 10 12]


In [10]:
mat = [[25, 36, 24] , [25 , 10 , 12]]
matriz = np.array(mat) # matriz 

print(type(matriz))
print(matriz)

<class 'numpy.ndarray'>
[[25 36 24]
 [25 10 12]]


In [11]:
cu = [[[1, 2], [36,0], [24,36]], [[19, 20], [368,20], [240,36]]]
cubo = np.array(cu)
print(cubo)

[[[  1   2]
  [ 36   0]
  [ 24  36]]

 [[ 19  20]
  [368  20]
  [240  36]]]


No hay límite de dimensiones para crear arrays

Otras formas de crear Arrays con Numpy 

In [12]:
## array vacío 
np.empty(3)

array([7.63918485e-313, 5.30498948e-313, 2.54639495e-313])

In [13]:
## Array de ceros 
np.zeros(3)

array([0., 0., 0.])

In [17]:
## array de unos 
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
## array con un patron predefinido
np.full((3,2), [2,3])

array([[2, 3],
       [2, 3],
       [2, 3]])

In [25]:
## array de identidad 
# una matriz identidad es una matriz cuadrada (nxn) con una diagonal de unos 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Rango de numeros (acepta decimales)  
# con el rango, creame los pasos, sin importar cuantos elementos tenga el resultado 

np.arange(0, 100, 2.3)
# np.arange y range 



array([ 0. ,  2.3,  4.6,  6.9,  9.2, 11.5, 13.8, 16.1, 18.4, 20.7, 23. ,
       25.3, 27.6, 29.9, 32.2, 34.5, 36.8, 39.1, 41.4, 43.7, 46. , 48.3,
       50.6, 52.9, 55.2, 57.5, 59.8, 62.1, 64.4, 66.7, 69. , 71.3, 73.6,
       75.9, 78.2, 80.5, 82.8, 85.1, 87.4, 89.7, 92. , 94.3, 96.6, 98.9])

In [31]:
# Espacio Lineal (no acepta decimales)
# con el rango, creame los pasos, que permitan dividir el rango en el numero de elementos definido
# max-min/n 
np.linspace(0, 100, 44)

array([  0.        ,   2.3255814 ,   4.65116279,   6.97674419,
         9.30232558,  11.62790698,  13.95348837,  16.27906977,
        18.60465116,  20.93023256,  23.25581395,  25.58139535,
        27.90697674,  30.23255814,  32.55813953,  34.88372093,
        37.20930233,  39.53488372,  41.86046512,  44.18604651,
        46.51162791,  48.8372093 ,  51.1627907 ,  53.48837209,
        55.81395349,  58.13953488,  60.46511628,  62.79069767,
        65.11627907,  67.44186047,  69.76744186,  72.09302326,
        74.41860465,  76.74418605,  79.06976744,  81.39534884,
        83.72093023,  86.04651163,  88.37209302,  90.69767442,
        93.02325581,  95.34883721,  97.6744186 , 100.        ])

In [33]:
# array con numero aleatorios 
np.random.random((5,3))*100

array([[26.78810056, 23.61405363, 57.75350795],
       [87.77698618, 37.32200833, 59.47660272],
       [47.1156561 , 98.5536544 , 75.05548821],
       [54.68292748, 80.81738022, 78.23269912],
       [ 9.87810211, 94.63158825, 72.79557299]])

### Atributos de los arrays

In [36]:
## obtener las dimensiones
espacio = np.random.random((5,3))
espacio.shape

(5, 3)

In [37]:
## obtener el número de elementos 
espacio.size

15

In [38]:
## obtener el tipo de los elementos 
espacio.dtype

dtype('float64')

#### Acceder a los elementos de un array (indexar)

In [40]:
espacio

array([[0.1336036 , 0.66446149, 0.02262617],
       [0.55296111, 0.42060311, 0.71103894],
       [0.39786423, 0.212374  , 0.12338817],
       [0.26902816, 0.00534501, 0.25799027],
       [0.45271775, 0.45549259, 0.86215026]])

In [42]:
espacio[2] #obtenemos el tercer elemento 

array([0.39786423, 0.212374  , 0.12338817])

In [43]:
espacio[2][0] #obtenemos el primer elemento del tercer elemento de la matriz 

0.39786423331391607

In [51]:
espacio[0:2, 0:2]

array([[0.1336036 , 0.66446149],
       [0.55296111, 0.42060311]])

In [57]:
#filtros en Numpy 
# nombre[condicion]

espacio[(espacio < 0.3) | (espacio > 0.7)]

array([0.1336036 , 0.02262617, 0.71103894, 0.212374  , 0.12338817,
       0.26902816, 0.00534501, 0.25799027, 0.86215026])

In [58]:
## Transposición de una matriz 
espacio.T

array([[0.1336036 , 0.55296111, 0.39786423, 0.26902816, 0.45271775],
       [0.66446149, 0.42060311, 0.212374  , 0.00534501, 0.45549259],
       [0.02262617, 0.71103894, 0.12338817, 0.25799027, 0.86215026]])

Ejercicio Rápido 
1. Generar un arreglo bidimensional NxM  
2. Recorrerlo y crear un arreglo nuevo, con los cuadrados de los elementos del arreglo inicial 

NOTA: no se vale hallar la potencia directamente 

In [61]:
## Bayron 
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = a
for k in range(len(a[0])):
    for h in range(len(a)):
      b[k][h] = a[k][h]*a[k][h]
    
print(*b, sep="\n")

[1, 4, 9]
[16, 25, 36]
[49, 64, 81]


In [ ]:
# Mauricio
numeros = [[1,2,3],[4,5,6], [7,8,9]]
array = np.array(numeros)
for i in range (len(array)):
    for j in range(len(array[i])):
        array[i][j]=array[i][j]**2
print(array)

In [ ]:
## Daniel Barros 
numFilas, numCol = matriz.shape
matriz2 = np.full([numFilas, numCol], 0)
for i in range(numFilas):
    for j in range(numCol):
        matriz2[i, j] = matriz[i, j] ** 2